### ISSUE TITLE
Can't to compile in linux + ogre3d-1.12.17

### ISSUE THREAD

**Issue by Joilnen** [MyGUI/mygui#205]
Scanning dependencies of target Common
[ 30%] Building CXX object Common/CMakeFiles/Common.dir/Base/Ogre/BaseManager.cpp.o
[ 30%] Building CXX object Common/CMakeFiles/Common.dir/Base/PlatformBaseManager/SdlBaseManager.cpp.o
[ 30%] Building CXX object Common/CMakeFiles/Common.dir/Input/SDL/InputManager.cpp.o
/home/joilnen/ogre3d_devel/mygui/Common/Base/Ogre/BaseManager.cpp: In member function ‘virtual bool base::BaseManager::createRender(int, int, bool)’:
/home/joilnen/ogre3d_devel/mygui/Common/Base/Ogre/BaseManager.cpp:76:12: error: ‘class Ogre::Camera’ has no member named ‘setPosition’; did you mean ‘getRealPosition’?
   76 |   mCamera->setPosition(400, 400, 400);
      |            ^~~~~~~~~~~
      |            getRealPosition
/home/joilnen/ogre3d_devel/mygui/Common/Base/Ogre/BaseManager.cpp:77:12: error: ‘class Ogre::Camera’ has no member named ‘lookAt’
   77 |   mCamera->lookAt(0, 150, 0);
      |            ^~~~~~
/home/joilnen/ogre3d_devel/mygui/Common/Base/Ogre/BaseManager.cpp:91:10: error: ‘class Ogre::Light’ has no member named ‘setDirection’
   91 |   light->setDirection(vec);
      |          ^~~~~~~~~~~~
make[2]: *** [Common/CMakeFiles/Common.dir/build.make:82: Common/CMakeFiles/Common.dir/Base/Ogre/BaseManager.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:723: Common/CMakeFiles/Common.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by Altren** [comment]
I don't know what is Ogre 1.12.17 (latest official release is 1.12.10), but it seems that your version does not have some deprecated functions, which are used in demos and tools, not the library itself.
MyGUI builds fine with the latest official Ogre release, though.

**Comment by Joilnen** [comment]
sorry it is 1.12.9 actually !

**Comment by Altren** [comment]
Should be fixed. The deprecated functions are still there (I'm using 1.12.10), and I don't know how to drop them.
Anyway I fixed most deprecated calls in master, please check.

**Comment by Altren** [comment]
@Joilnen Did you tried with the latest master?

**Comment by Joilnen** [comment]
Yes it is working fine, I compiled demos and ran them ok !
