### ISSUE TITLE
Compilation errors with OGRE 1.11.0

### ISSUE THREAD

**Issue by dschepler** [MyGUI/mygui#147]
When I try building against OGRE 1.11.0 (after fixing `Platforms/Ogre/OgrePlatform/CMakeLists.txt` to use `${OGRE_INCLUDE_DIRS}` instead of `${OGRE_INCLUDE_DIR}` ) I get compilation errors like:

```
In file included from /home/dschepler/scalable-3p/scalable-3p-mygui/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreTexture.cpp:10:0:
/home/dschepler/scalable-3p/scalable-3p-mygui/Platforms/Ogre/OgrePlatform/include/MyGUI_OgreRenderManager.h:25:35: error: expected class-name before ',' token
   public Ogre::WindowEventListener,
                                   ^
In file included from /home/dschepler/scalable-3p/scalable-3p-mygui/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRenderManager.cpp:8:0:
/home/dschepler/scalable-3p/scalable-3p-mygui/Platforms/Ogre/OgrePlatform/include/MyGUI_OgreRenderManager.h:25:35: error: expected class-name before ',' token
   public Ogre::WindowEventListener,
                                   ^
In file included from /home/dschepler/scalable-3p/scalable-3p-mygui/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRTTexture.cpp:9:0:
/home/dschepler/scalable-3p/scalable-3p-mygui/Platforms/Ogre/OgrePlatform/include/MyGUI_OgreRenderManager.h:25:35: error: expected class-name before ',' token
   public Ogre::WindowEventListener,
                                   ^
/home/dschepler/scalable-3p/scalable-3p-mygui/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRenderManager.cpp: In member function 'void MyGUI::OgreRenderManager::setRenderWindow(Ogre::RenderWindow*)':
/home/dschepler/scalable-3p/scalable-3p-mygui/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRenderManager.cpp:127:10: error: 'Ogre::WindowEventUtilities' has not been declared
    Ogre::WindowEventUtilities::removeWindowEventListener(mWindow, this);
          ^~~~~~~~~~~~~~~~~~~~
/home/dschepler/scalable-3p/scalable-3p-mygui/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRenderManager.cpp:135:10: error: 'Ogre::WindowEventUtilities' has not been declared
    Ogre::WindowEventUtilities::addWindowEventListener(mWindow, this);
          ^~~~~~~~~~~~~~~~~~~~
/home/dschepler/scalable-3p/scalable-3p-mygui/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRenderManager.cpp: In member function 'void MyGUI::OgreRenderManager::setActiveViewport(short unsigned int)':
/home/dschepler/scalable-3p/scalable-3p-mygui/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRenderManager.cpp:169:10: error: 'Ogre::WindowEventUtilities' has not been declared
    Ogre::WindowEventUtilities::removeWindowEventListener(mWindow, this);
          ^~~~~~~~~~~~~~~~~~~~
/home/dschepler/scalable-3p/scalable-3p-mygui/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRenderManager.cpp:170:10: error: 'Ogre::WindowEventUtilities' has not been declared
    Ogre::WindowEventUtilities::addWindowEventListener(mWindow, this);
          ^~~~~~~~~~~~~~~~~~~~
```

Adding `#include <Bites/OgreWindowEventUtilities.h>` to `Platforms/Ogre/OgrePlatform/include/MyGUI_OgreRenderManager.h` seems to fix the compilation.

**Comment by laomaiweng** [comment]
Sorry for going slightly off-topic, but what's that about fixing `CMakeLists.txt` to use `${OGRE_INCLUDE_DIRS}`? I think I'm being bit by this bug, but can't find any relevant issue or PR about it.

**Comment by steils** [comment]
+1 to compilation errors with OGRE 1.11.0, but slightly different.

After upgrading OGRE to 1.11.0 got this:

```
[ 27%] Building CXX object Platforms/Ogre/OgrePlatform/CMakeFiles/MyGUI.OgrePlatform.dir/src/MyGUI_OgreDataManager.cpp.o
In file included from /home/stefan/projects/mygui/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreDataManager.cpp:9:
/home/stefan/projects/mygui/Platforms/Ogre/OgrePlatform/include/MyGUI_OgreDataStream.h:13:10: fatal error: OgreDataStream.h: No such file or directory
 #include <OgreDataStream.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Platforms/Ogre/OgrePlatform/CMakeFiles/MyGUI.OgrePlatform.dir/build.make:63: Platforms/Ogre/OgrePlatform/CMakeFiles/MyGUI.OgrePlatform.dir/src/MyGUI_OgreDataManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:164: Platforms/Ogre/OgrePlatform/CMakeFiles/MyGUI.OgrePlatform.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

If I change `${OGRE_INCLUDE_DIR}` to `${OGRE_INCLUDE_DIRS}` in `Platforms/Ogre/OgrePlatform/CMakeLists.txt` I get this:
```
[ 27%] Building CXX object Platforms/Ogre/OgrePlatform/CMakeFiles/MyGUI.OgrePlatform.dir/src/MyGUI_OgreDataManager.cpp.o
/home/stefan/projects/mygui/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreDataManager.cpp: In member function ‘const VectorString& MyGUI::OgreDataManager::getDataListNames(const string&, bool)’:
/home/stefan/projects/mygui/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreDataManager.cpp:109:15: error: ‘Ogre::FileInfoListPtr’ {aka ‘class std::shared_ptr<std::vector<Ogre::FileInfo, std::allocator<Ogre::FileInfo> > >’} has no member named ‘setNull’
     pFileInfo.setNull();
               ^~~~~~~
/home/stefan/projects/mygui/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreDataManager.cpp:137:14: error: ‘Ogre::FileInfoListPtr’ {aka ‘class std::shared_ptr<std::vector<Ogre::FileInfo, std::allocator<Ogre::FileInfo> > >’} has no member named ‘setNull’
    pFileInfo.setNull();
              ^~~~~~~
make[2]: *** [Platforms/Ogre/OgrePlatform/CMakeFiles/MyGUI.OgrePlatform.dir/build.make:63: Platforms/Ogre/OgrePlatform/CMakeFiles/MyGUI.OgrePlatform.dir/src/MyGUI_OgreDataManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:164: Platforms/Ogre/OgrePlatform/CMakeFiles/MyGUI.OgrePlatform.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by steils** [comment]
Heh :-)
```
        /// @deprecated use SharedPtr::operator unspecified_bool_type() instead
        OGRE_DEPRECATED bool isNull(void) const { return pRep == 0; }

        /// @deprecated use reset() instead
        OGRE_DEPRECATED void setNull() { reset(); }
```

Following the recommendations fixes compilation for me.
So... Should I consider this issue different from #147? Should I open a new one?

**Comment by steils** [comment]
Oh, my issue is with Ogre 1.10, this one is 1.11...

**Comment by Altren** [comment]
Fixes
